version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-multi-function-test"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-vn6jgi0d56lp"
s3_prefix = "sam-multi-function-test"
region = "eu-west-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"Dev\""

