AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  sam-multi-function-test

  Sample SAM Template for sam-multi-function-test

Parameters:
  Application:
    Type: String
    Default: FlowPrototype
  Environment:
    Type: String
        
# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3

Resources:

  RequestResponseTopic:
    Type: AWS::SNS::Topic
    Properties:
      TopicName: !Sub ${Environment}-${Application}-RequestResponseTopic
      DisplayName: Topic for request & response messages

  FlowInstanceTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: !Sub ${Environment}-${Application}-FlowInstanceTable

  FlowWireTapFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-${Application}-FlowWireTap
      CodeUri: test-flow/
      Handler: FlowWireTap.handler
      Runtime: nodejs12.x
      Events:
        NotificationTopic:
          Type: SNS
          Properties:
            Topic: !Ref RequestResponseTopic

  AddActivityFunction: # We know this in the handler
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-${Application}-AddActivity # We know this in the handler
      CodeUri: test-flow/ # How can we populate this? I guess we know it if we are running a test
      Handler: AddActivity.handler # We know this in the handler
      Runtime: nodejs12.x # We can default this
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt RequestResponseTopic.TopicName
      Environment:
        Variables:
          REQUEST_RESPONSE_TOPIC_ARN: !Ref RequestResponseTopic
      Events:
        NotificationTopic:
          Type: SNS
          Properties:
            Topic: !Ref RequestResponseTopic
            FilterPolicy:
              MessageType:
                - Add:Request

  AddFlowFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${Environment}-${Application}-AddFlow
      CodeUri: test-flow/
      Handler: AddFlow.handler
      Runtime: nodejs12.x
      Policies:
        - SNSPublishMessagePolicy:
            TopicName: !GetAtt RequestResponseTopic.TopicName
        - DynamoDBCrudPolicy:
            TableName: !Ref FlowInstanceTable
      Environment:
        Variables:
          REQUEST_RESPONSE_TOPIC_ARN: !Ref RequestResponseTopic
          FLOW_INSTANCE_TABLE_NAME: !Ref FlowInstanceTable
      Events:
        NotificationTopic:
          Type: SNS
          Properties:
            Topic: !Ref RequestResponseTopic
            FilterPolicy:
              MessageType:
                - AddFlow:Request
                - AddFlow:Response

Outputs:

  FlowInstanceTable:
    Description: "ARN"
    Value: !GetAtt FlowInstanceTable.Arn

  AddActivityFunction:
    Description: "ARN"
    Value: !GetAtt AddActivityFunction.Arn

  AddFlowFunction:
    Description: "ARN"
    Value: !GetAtt AddFlowFunction.Arn
